<?php $this->formRadio()->setSeparator('</div><div class="radio-inline">'); ?>

<div class="container">
	<h2><?php echo sprintf($this->translate('Produkt hizufügen')) ?></h2>
	<?php echo $this->form()->openTag($form); ?>
		<div class="form-group">
			<?php echo $this->formLabel($form->get('kategorieId')) ?>
			<div class="col-sm-3">
				<?php echo $this->formelement($form->get('kategorieId')); ?>
			</div>
		</div>
		<div class="form-group">
			<?php echo $this->formLabel($form->get('produktartId')) ?>
			<div class="col-sm-3">
				<?php echo $this->formelement($form->get('produktartId')); ?>
			</div>
		</div>
		<div class="form-group">
			<?php echo $this->formLabel($form->get('produktame')) ?>
			<div class="col-sm-3">
				<?php echo $this->formelement($form->get('produktame')); ?>
			</div>
		</div>	
		<div class="form-group">
			<?php echo $this->formLabel($form->get('bankId')) ?>
			<div class="col-sm-3">
				<?php echo $this->formelement($form->get('bankId')); ?>
			</div>
		</div>				
		<div class="form-group">
			<?php echo $this->formLabel($form->get('produktHasOnlineAbschluss')) ?>
			<div class="col-sm-3">
				<div class="radio-inline">
					<?php echo $this->formradio($form->get('produktHasOnlineAbschluss')); ?>
				</div>
			</div>
		</div>	
		<div class="form-group">
			<?php echo $this->formLabel($form->get('produktMindestanlage')) ?>
			<div class="col-sm-3">
				<?php echo $this->formelement($form->get('produktMindestanlage')); ?>
			</div>
		</div>
		<div class="form-group">
			<?php echo $this->formLabel($form->get('produktHoechstanlage')) ?>
			<div class="col-sm-3">
				<?php echo $this->formelement($form->get('produktHoechstanlage')); ?>
			</div>
		</div>	
		<div class="form-group">
			<?php echo $this->formLabel($form->get('produktHasGesetzlEinlagvers')) ?>
			<div class="col-sm-3">
				<div class="radio-inline">
					<?php echo $this->formradio($form->get('produktHasGesetzlEinlagvers')); ?>
				</div>
			</div>
		</div>	
		<div class="form-group">
			<?php echo $this->formLabel($form->get('aktionId')) ?>
			<div class="col-sm-3">
				<?php echo $this->formelement($form->get('aktionId')); ?>
			</div>
		</div>								
	<?php echo $this->form()->closeTag(); ?>
</div>