<h2><?php echo sprintf($this->translate($form->getLabel())) ?></h2>
<?php
	echo $this->headLink()
		->prependStylesheet($this->basePath() . '/scripts/bootstrap/plugins/bootstrap-datetimepicker/css/bootstrap-datetimepicker.min.css');
	echo $this->headScript()
		->prependFile($this->basePath() . '/scripts/product.js')
		->prependFile($this->basePath() . '/scripts/bootstrap/plugins/bootstrap-maxlength.min.js')
		->prependFile($this->basePath() . '/scripts/bootstrap/plugins/bootstrap-datetimepicker/js/locales/bootstrap-datetimepicker.de.js')
		->prependFile($this->basePath() . '/scripts/bootstrap/plugins/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js');
	echo $this->form()->openTag($form);
?>
<input type="hidden" value="<?php echo $produktId ?>" class="produktId"/>

<?php foreach ($form as $element) :?>
	    <div class="form-group">
	        <?php
	            $type = $element->getAttribute('type');
	            $name = $element->getAttribute('name'); 
	            $label = $element->getLabel();
	        ?>
	        	<?php 
	        		if($type != 'button') echo $this->formLabel($element); 
	        		else { ?> <div class="col-sm-3"></div> <?php }
	        	?>
	        	<div class="col-sm-3">
	        		<?php 
        				echo $this->formElement($element);
        			?>
	        	</div>
	    </div>
<?php endforeach; ?>
<?php echo $this->form()->closeTag(); ?>

<!-- Modal -->
<div class="modal fade" id="konditionen-bearbeiten-modal" tabindex="-1" role="dialog" aria-labelledby="konditionen-bearbeiten-modal-label" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title" id="konditionen-bearbeiten-modal-label">Konditionen bearbeiten</h4>
			</div>
			<div class="modal-body">
				<form action="" method="post" id="konditionen-modal-form" role="form">
	            	<div class="alert" id="alert-modal">
	            		<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
	            		<div id="alert-modal-message"></div>
	            	</div>
					<input type="hidden" value="<?php echo $produktId ?>" class="produktId"/>
					<div class="table-responsive">
						<table class="table table-condensed table-hover" id="konditionen-table">
							<thead>
								<tr>
									<th>Laufzeit</th>
									<th>Einlage von</th>
									<th>Einlage bis</th>
									<th>Zinssatz</th>
									<th></th>
								</tr>
							</thead>
							<tbody>
								<tr>
									<td>
										<input type="text" class="form-control kondition-laufzeit">
									</td>
									<td>
										<input type="text" class="form-control kondition-einlage-von">
									</td>
									<td>
										<input type="text" class="form-control kondition-einlage-bis">
									</td>
									<td>
										<input type="text" class="form-control kondition-zinssatz">
									</td>
									<td>
										<button type="button" class="btn btn-danger" disabled><span class="glyphicon glyphicon-remove"></span></button>
									</td>
								</tr>
							</tbody>
							<tfoot>
								<tr>
									<td>in Monaten</td>
									<td>in €</td>
									<td>in €</td>
									<td>in %</td>
									<td>
										<button type="button" class="btn btn-success pull-right" id="add-kondition">
											<span class="glyphicon glyphicon-plus"></span>
										</button>
									</td>
								</tr>
							</tfoot>
						</table>
					</div>
				</form>
			</div>
			<div class="modal-footer">
 				<button type="button" class="btn btn-default" data-dismiss="modal">Schließen</button>
				<button type="button" class="btn btn-primary" id="save-konditionen">Übernehmen</button>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->
