<h2><?php echo sprintf($this->translate($form->getLabel())) ?></h2>
<?php
	echo $this->headLink()
		->prependStylesheet($this->basePath() . '/scripts/bootstrap/plugins/bootstrap-datetimepicker/css/bootstrap-datetimepicker.min.css');
	echo $this->headScript()
		->prependFile($this->basePath() . '/scripts/product.js')
		->prependFile($this->basePath() . '/scripts/bootstrap/plugins/bootstrap-maxlength.min.js')
		->prependFile($this->basePath() . '/scripts/bootstrap/plugins/bootstrap-datetimepicker/js/locales/bootstrap-datetimepicker.de.js')
		->prependFile($this->basePath() . '/scripts/bootstrap/plugins/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js');
	echo $this->form()->openTag($form);
?>
<input type="hidden" value="<?php echo $produktId ?>" class="produktId"/>

<?php foreach ($form as $element) :?>
	    <div class="form-group">
	        <?php
	            $type = $element->getAttribute('type');
	            $name = $element->getAttribute('name'); 
	            $label = $element->getLabel();
	        ?>
	        	<?php 
	        		if($type != 'button') echo $this->formLabel($element); 
	        		else { ?> <div class="col-sm-3"></div> <?php }
	        	?>
	        	<div class="col-sm-3">
	        		<?php 
// 	        			if($name == 'produktGueltigSeit') echo $this->formDateSelect($form->get('produktGueltigSeit'), IntlDateFormatter::LONG, 'de_DE');
// 	        			else 
	        				echo $this->formElement($element);
        			?>
	        	</div>
	    </div>
<?php endforeach; ?>
<?php echo $this->form()->closeTag(); ?>
