<?php 
	echo $this->headScript()
		->prependFile($this->basePath() . '/scripts/product-overview.js')
		->prependFile($this->basePath() . '/scripts/tablesorter/js/jquery.tablesorter.widgets.min.js')
		->prependFile($this->basePath() . '/scripts/tablesorter/addons/pager/jquery.tablesorter.pager.min.js')
		->prependFile($this->basePath() . '/scripts/tablesorter/js/jquery.tablesorter.min.js');
	echo $this->headLink()
		->prependStylesheet($this->basePath() . '/css/product-overview.css')
		->prependStylesheet($this->basePath() . '/scripts/tablesorter/addons/pager/jquery.tablesorter.pager.css')
		->prependStylesheet($this->basePath() . '/scripts/tablesorter/css/theme.bootstrap.css');
?>
<div class="row text-center">
  	<h2><?php echo sprintf($this->translate('Produktübersicht')) ?></h2>
</div>	
<div class="row text-center">
	<p><a class="btn btn-success" href="produkt/edit"><?php echo $this->translate('Produkt hizufügen') ?></a></p>
</div>	
<div class="row">
	<table class="table-hover tablesorter" id="produkte-table">
		<thead>
			<tr>
				<th></th>
				<th data-placeholder="Suche nach Produktnamen...">Produktname</th>
				<th class="filter-select" data-placeholder="Suche nach Kategorie...">Kategorie</th>
				<th class="filter-select" data-placeholder="Suche nach Bank...">Bank</th>
				<th>Tipp</th>
				<th>Klickout-URL</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach($produkte as $produkt): ?>
				<tr>
					<td>
						<input type="hidden" value="<?php echo $produkt->getProduktId(); ?>" class="produktId"/>
						<a href="produkt/edit/<?php echo $produkt->getProduktId(); ?>" class="btn btn-default btn-xs edit-produkt-button">
							<span class="glyphicon glyphicon-pencil"></span>
						</a>
						<button type="button" class="btn btn-default btn-xs delete-produkt-button">
							<span class="glyphicon glyphicon-trash"></span>
						</button>
					</td>
					<td>
						<span><?php echo $produkt->getProduktName(); ?></span>
						<div>
							Produkt-URL: <a href="<?php echo $produkt->getProduktUrl() ?>">
											<?php echo $produkt->getProduktUrl() ?>
										</a>
						</div>
					</td>				
					<td><?php echo $produkt->getKategorie()->getKategorieName() ?></td>				
					<td>	
						<img 
							alt="<?php echo $produkt->getBank()->getBankName() ?>" 
							src="uploads/bank-logo/<?php echo $produkt->getBank()->getBankLogo() ?>"
							class="bank-logo-preview"
						/>
						<br/>
						<?php echo $produkt->getBank()->getBankName() ?>
					</td>				
					<td>
						<?php if($produkt->getProduktTipp()): ?>
							<span class="glyphicon glyphicon-ok"></span>
						<?php else: ?>
							<span class="glyphicon glyphicon-remove"></span>
						<?php endif; ?>
					</td>				
					<td><?php echo $produkt->getProduktKlickoutUrl() ?></td>	
				</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
</div>