<?php 
	echo $this->headScript()
		->prependFile($this->basePath() . '/scripts/erfahrung.js')
		->prependFile($this->basePath() . '/scripts/tablesorter/js/jquery.tablesorter.widgets.min.js')
		->prependFile($this->basePath() . '/scripts/tablesorter/addons/pager/jquery.tablesorter.pager.min.js')
		->prependFile($this->basePath() . '/scripts/raty/jquery.raty.js')
		->prependFile($this->basePath() . '/scripts/tablesorter/js/jquery.tablesorter.min.js');
	echo $this->headLink()
		->prependStylesheet($this->basePath() . '/css/erfahrung.css')
		->prependStylesheet($this->basePath() . '/scripts/tablesorter/addons/pager/jquery.tablesorter.pager.css')
		->prependStylesheet($this->basePath() . '/scripts/tablesorter/css/theme.bootstrap.css');
	date_default_timezone_set('Europe/Berlin');
?>

<div class="row sort-row">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3>Filtern & Sortieren</h3>
			</div>
			<div class="panel-body">
				<div class="row">
					<form role="form">
						<div class="col-xs-6">
							<div class="form-group">
						    	<label for="bank-filter">Bank</label>
					    		<select id="bank-filter" class="form-control" >
									<option value="">Alle</option>
									<?php 
										foreach($banken as $bank){
											echo "<option value='".$bank->getBankName()."'>".$bank->getBankName()."</option>";
										}
									?>
								</select>
						  	</div>
						</div>	
						<div class="col-xs-6">
							<div class="form-group">
						    	<label for="status-filter">Status</label>
					    		<select id="status-filter" class="form-control" >
									<option value="">Alle</option>
									<option value="nicht freigeschaltet">nicht freigeschaltet</option>
									<option value="freigeschaltet">freigeschaltet</option>
								</select>
						  	</div>
						</div>	
					</form>	
				</div>
				<div class="row">
					<form role="form">
						<div class="col-xs-6">
							<div class="form-group">
						    	<label for="note-filter">Bewertung</label>
					    		<select id="note-filter" class="form-control" >
									<option value="">Alle</option>
									<option value="1">1 Stern</option>
									<option value="2">2 Sterne</option>
									<option value="3">3 Sterne</option>
									<option value="4">4 Sterne</option>
									<option value="5">5 Sterne</option>
								</select>
						  	</div>
						</div>	
						<div class="col-xs-6">
							<div class="form-group">
						    	<label for="datum-filter">Alter (coming soon)</label>
					    		<select id="datum-filter" class="form-control" disabled="disabled">
									<option value="">Alle</option>
									<option value="<?php echo date('d.m.Y'); ?>">von heute</option>
									<option value="<?php echo date('d.m.Y', time() - 60 * 60 * 24); ?>">von gestern</option>
									<option value="">< 7 Tage</option>
									<option value="">< 14 Tage</option>
								</select>
						  	</div>
						</div>	
					</form>	
				</div>				
				<div class="row">
					<div class="col-xs-6">
						<button id="sort-on-status" class="btn btn-primary btn-block sort-button" type="button">Nach Status sortieren</button>
					</div>
					<div class="col-xs-6">
						<button id="sort-on-date" class="btn btn-primary btn-block sort-button" type="button">Nach Datum sortieren</button>
					</div>
				</div>								
			</div>
		</div>
</div>

<div class="row">
	<table class="table-hover tablesorter" id="erfahrungen-table">
		<thead>
			<tr>
				<th class="status-hidden">Bank</th>
				<th>Bericht</th>
				<th class="status-hidden">Bewertung</th>
				<th class="status-hidden">Status</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach($erfahrungen as $erfahrung): ?>
				<tr id="erfahrungen-table-row-<?php echo $erfahrung->getErfahrungId(); ?>">
					<td class="column-hidden">
						<span class="erfahrung-bank">
							<?php echo $erfahrung->getBank()->getBankName(); ?>
						</span>
					</td>
					<td>	
						<div class="panel panel-default" id="bericht-<?php echo $erfahrung->getErfahrungId(); ?>">
							<div class="panel-heading">
								<div class="row">
									<div class="col-xs-3">
										<div class="col-xs-6">Bericht über:</div>
										<div class="col-xs-6">
											<?php if($erfahrung->getBank()->getBankLogo() != null):?>
												<img 
													src="../uploads/bank-logo/<?php echo $erfahrung->getBank()->getBankLogo().'_115-x-60.png' ?>"
													alt="<?php echo $erfahrung->getBank()->getBankName(); ?>"
												/>
											<?php else:?>
												<span><?php echo $erfahrung->getBank()->getBankName(); ?></span>
											<?php endif;?>
										</div>								
									</div>
									<div class="col-xs-9">
										<div class="row">
											<div class="col-xs-2">Verfasst von:</div>  
											<div class="col-xs-6">
												<?php 
													$benutzername = $erfahrung->getErfahrungAutorUserName() == null ? '' : 'aka '.$erfahrung->getErfahrungAutorUserName();
													echo sprintf("%s %s %s (<a href='mailto:%s'>%s</a>)", 
														$erfahrung->getErfahrungAutorVorname(),
														$erfahrung->getErfahrungAutorName(),
														$benutzername,
														$erfahrung->getErfahrungAutorEmail(),
														$erfahrung->getErfahrungAutorEmail()
													);
												?>
											</div>
											<div class="col-xs-4">
												<div class="row">
													<div class="col-xs-6">
													</div>
													<div class="col-xs-6">
														<a href="#" class="erfahrung-delete pull-right" onclick="alert('Coming soon!');">
															Bericht löschen
														</a>
													</div>
												</div>
											</div>
										</div>
										<div class="row">
											<div class="col-xs-2">Verfasst am:</div>  
											<div class="col-xs-5">
												<span class="verfasst-am"><?php echo $erfahrung->getErfahrungDatum()->format('d.m.Y H:i:s');?></span>	
											</div>
											<div class="col-xs-5">
												<div class="row">
													<div class="col-xs-2">
														Status:
													</div>
													<div class="col-xs-10">
														<?php 
															switch($erfahrung->getErfahrungIsFreigeschaltet()){
																case true:
																	echo "
																		<button class='btn btn-success btn-xs status-switch' type='button'>
																			<span class='glyphicon glyphicon-ok' title='freigescheltet'></span>
																		</button>";
																	break;
																case false:
																	echo "
																		<button class='btn btn-danger btn-xs status-switch' type='button'>
																			<span class='glyphicon glyphicon-remove' title='nicht freigescheltet'></span>
																		</button>";									
																	break;
															}
														?>	
													</div>	
												</div>							
											</div>
										</div>
									</div>
								</div>
							</div>
							<div class="panel-body">
								<?php echo $erfahrung->getErfahrungBericht() ?>
							</div>
							<div class="panel-footer">
								<div class="row">
									<div class="col-xs-4">
										<div class="row">
											<div class="col-xs-6">
												Bewertung:
											</div>
											<div class="col-xs-6">
												<div class="bewertung" id="bewertung-<?php echo $erfahrung->getErfahrungNote() ?>"></div>
											</div>
										</div>
									</div>  
									<div class="col-xs-4">
										<div class="row">
											<div class="col-xs-6">
												Bankempfehlung:
											</div>
											<div class="col-xs-6">
												<?php 
													switch($erfahrung->getErfahrungEmpfBank()){
														case 0:
															echo "<span class='glyphicon glyphicon-thumbs-down' title='Nein'></span>";
															break;
														case 1: 
															echo "<span class='glyphicon glyphicon-thumbs-up' title='Ja'></span>";
															break;
														case 2:
															echo "<span class='glyphicon glyphicon-adjust' title='Vieleicht'></span>";
															break;
													} 
												?>
											</div>
										</div>
									</div>
									<div class="col-xs-4">
										<div class="row">
											<div class="col-xs-6">
												Produktempfehlung:
											</div>
											<div class="col-xs-6">	
												<?php 
													switch($erfahrung->getErfahrungEmpfProdukt()){
														case 0:
															echo "<span class='glyphicon glyphicon-thumbs-down' title='Nein'></span>";
															break;
														case 1:
															echo "<span class='glyphicon glyphicon-thumbs-up' title='Ja'></span>";
															break;
														case 2:
															echo "<span class='glyphicon glyphicon-adjust' title='Vieleicht'></span>";
															break;
													} 
												?>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</td>
					<td class="column-hidden">
						<span class="erfahrung-note" id="note-<?php echo $erfahrung->getErfahrungId(); ?>">
							<?php echo $erfahrung->getErfahrungNote(); ?>
						</span>					
					</td>
					<td class="column-hidden">
						<span class="erfahrung-status" id="status-<?php echo $erfahrung->getErfahrungId(); ?>">
							<?php echo $erfahrung->getErfahrungIsFreigeschaltet() == false ? 'nicht freigeschaltet' : 'freigeschaltet' ?>
						</span>
					</td>	
				</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
</div>