<div class="jumbotron">
    <h1><?php echo $this->translate('Willkommen zur Admin-Konsole') ?></h1>
</div>

<div class="row">

    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Produktverwaltung') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo $this->translate('Hier kannst du die neue Produkte hinzufügen oder vorhandene bearbeiten.') ?></p>
                <p><a class="btn btn-success pull-right" href="produktverwaltung"><?php echo $this->translate('Produktverwaltung') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Datenbankverwaltung') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo $this->translate('Hier kannst du die Datenbanktabellen verwalten und befüllen.') ?></p>
                <p><a class="btn btn-success pull-right" href="database"><?php echo $this->translate('Datenbankverwaltung') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Erfahrungsberichte') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo $this->translate('Hier kannst du die Erfahrungsberichte zu den Banken freischalten oder löschen.') ?></p>
                <p><a class="btn btn-success pull-right" href="erfahrungsberichte"><?php echo $this->translate('Erfahrungsberichte') ?> &raquo;</a></p>
            </div>
        </div>
    </div>    
</div>
