<h2><?php echo sprintf($this->translate($form->getLabel())) ?></h2>
<?php
	echo $this->headLink()
		->prependStylesheet($this->basePath() . '/scripts/bootstrap/plugins/bootstrap-datetimepicker/css/bootstrap-datetimepicker.min.css')
		->prependStylesheet($this->basePath() . '/css/kredit.css');
	echo $this->headScript()
		->prependFile($this->basePath() . '/scripts/kredit.js')
		->prependFile($this->basePath() . '/scripts/bootstrap/plugins/bootstrap-maxlength.min.js')
		->prependFile($this->basePath() . '/scripts/bootstrap/plugins/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js')
		->prependFile($this->basePath() . '/scripts/moment-with-langs.min.js')
		->appendFile($this->basePath() . '/scripts/bootstrap/plugins/gridline.min.js');
	echo $this->form()->openTag($form);
?>
<input type="hidden" value="<?php echo $produktId ?>" class="produktId"/>

<?php foreach ($form as $element) :?>
	    <div class="form-group">
	        <?php
	            $type = $element->getAttribute('type');
	            $name = $element->getAttribute('name'); 
	            $label = $element->getLabel();
	        ?>
	        	<?php 
	        		if($type == 'button') { ?> <div class="col-sm-3"></div> <?php }
	        		elseif($type == 'hidden') {}
	        		else echo $this->formLabel($element); 
	        	?>
	        	<div class="col-sm-3">
	        		<?php 
        				if($name == 'produktMinKredit' || 
						   $name == 'produktMaxKredit' ||
						   $name == 'produktBearbeitungsgebuehr'){ 
        					echo '
								<div class="input-group">'.
				  					$this->formElement($element)
				  					.'<span class="input-group-addon"><i class="glyphicon glyphicon-euro"></i></span>
								</div>';
        					if($name == 'produktMaxKredit') echo '<span class="help-block">0 = unbegrenzt</span>';
        				} else {
							echo $this->formElement($element);
						}
        			?>
	        	</div>
	    </div>
<?php endforeach; ?>
<!-- <button type="button" class="btn" id="fill-produkt"> -->
<!-- 	Fill -->
<!-- </button> -->
<?php echo $this->form()->closeTag(); ?>

<!-- Modal -->
<div class="modal large fade" id="konditionen-bearbeiten-modal" tabindex="-1" role="dialog" aria-labelledby="konditionen-bearbeiten-modal-label" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title" id="konditionen-bearbeiten-modal-label">Konditionen bearbeiten</h4>
			</div>
			<div class="modal-body">
				<form action="" method="post" id="konditionen-modal-form" role="form">
	            	<div class="alert" id="alert-modal">
	            		<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
	            		<div id="alert-modal-message"></div>
	            	</div>
            		<div class="progress progress-striped active">
						<div class="progress-bar modal-progress-bar" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100"></div>
					</div>
					
					<input type="hidden" value="<?php echo $produktId ?>" class="produktId"/>
					
					<div class="row">
						<label class="col-sm-3 control-label" for="produktIsBonitabh-helper">Bonitätsabhängig?</label>
						<div class="col-sm-3">
							<label class="radio-inline">
								<input type="radio" value="1" name="produktIsBonitabh-helper">
								Ja
							</label>
							<label class="radio-inline">
								<input type="radio" value="0" name="produktIsBonitabh-helper">
								Nein
							</label>
						</div>
					</div>			
							
					<div class="table-responsive"></div>
				</form>
			</div>
			<div class="modal-footer">
<!-- 				<button type="button" class="btn btn-default" id="fill">Füllen</button> -->
 				<button type="button" class="btn btn-default" data-dismiss="modal" id="close-konditionen-modal">Schließen</button>
				<button type="button" class="btn btn-primary" id="save-konditionen">Übernehmen</button>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->
