<h2><?php echo sprintf($this->translate($form->getLabel())) ?></h2>
<?php
$this->headLink()
        ->prependStylesheet($this->basePath() . '/scripts/bootstrap/plugins/bootstrap-datetimepicker/css/bootstrap-datetimepicker.min.css')
        ->prependStylesheet($this->basePath() . '/css/kredit.css')
        ->prependStylesheet($this->basePath() . '/scripts/summernote/summernote.css')
;
$this->headScript()
        ->prependFile($this->basePath() . '/scripts/kredit.js')
        ->prependFile($this->basePath() . '/scripts/bootstrap/plugins/bootstrap-maxlength.min.js')
        ->prependFile($this->basePath() . '/scripts/bootstrap/plugins/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js')
        ->prependFile($this->basePath() . '/scripts/moment-with-langs.min.js')
        ->appendFile($this->basePath() . '/scripts/bootstrap/plugins/gridline.min.js')
        ->appendFile($this->basePath() . '/scripts/summernote/summernote.min.js')
        ->appendFile($this->basePath() . '/scripts/summernote/summernote-de-DE.js')
;

$panelProperties = array(
    'kategorie' => array(
        'id' => 'pflichtfelder',
        'text' => 'Pflichtfelder'
    ),
    'aktion' => array(
        'id' => 'allgemeine-eigenschaften',
        'text' => 'Allgemeine Eigenschaften (optional)'
    ),
    'produktMinKredit' => array(
        'id' => 'kredit-eigenschaften',
        'text' => 'Krediteigenschaften (optional)'
    ),
    'produktInformationen' => array(
        'id' => 'informationen',
        'text' => 'Informationen'
    ),
    'produktLaufzeit' => array(
        'id' => 'repr-beispiel',
        'text' => 'Repräsentatives Beispiel'
    ),
);
?>
<div class="row">
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
        <?php echo $this->form()->openTag($form); ?>
        <input type="hidden" value="<?php print($produktId); ?>" class="produktId"/>

        <?php
        foreach ($form as $element) :
            $type = $element->getAttribute('type');
            $name = $element->getAttribute('name');
            $label = $element->getLabel();

            if ($name == 'kategorie' ||
                    $name == 'aktion' ||
                    $name == 'produktMinKredit' ||
                    $name == 'produktInformationen' ||
                    $name == 'produktLaufzeit'):
                ?>
                <div class='panel panel-default'>
                    <div class='panel-heading' id='<?php print($panelProperties[$name]['id']); ?>'>
                        <?php print($panelProperties[$name]['text']); ?>
                    </div>
                    <div class='panel-body'>
                    <?php endif; ?>
                    <div class="form-group">
                        <?php
                        if ($name != 'produktKtofuehrKostFllg' && $name != 'produktWiderrufsfristZeiteinh'):
                            print($this->formLabel($element));
                        endif;
                        ?>
                        <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
                            <?php
                            if ($name == 'produktMinKredit' ||
                                    $name == 'produktMaxKredit' ||
                                    $name == 'produktBearbeitungsgebuehr' ||
                                    $name == 'produktGesamtbetrag' ||
                                    $name == 'produktNettokreditsumme'):
                                ?>
                                <div class="input-group">
                                    <?php print($this->formElement($element)); ?>
                                    <span class="input-group-addon"><i class="glyphicon glyphicon-euro"></i></span>
                                </div>
                                <?php if ($name == 'produktMaxKredit'): ?>
                                    <span class="help-block">0 = unbegrenzt</span>
                                    <?php
                                endif;
                            elseif ($name == 'produktSollzins' ||
                                    $name == 'produktEffektiverJahreszins'):
                                ?>
                                <div class="input-group">
                                    <?php print($this->formElement($element)); ?>
                                    <span class="input-group-addon">%</span>
                                </div>
                            <?php elseif ($name == 'produktUrl') : ?>
                                <div class='input-group'>
                                    <span class='input-group-addon'>http://www.vergleich24.at/</span>
                                    <?php print($this->formElement($element)); ?>
                                </div>
                                <?php if ($name == 'produktHoechstanlage'): ?>
                                    <span class="help-block">0 = unbegrenzt</span>
                                <?php endif; ?>
                            <?php elseif ($name == 'produktKtofuehrKost'):
                                ?>
                                <div class="input-group">
                                    <?php print($this->formElement($element)); ?>
                                    <span class="input-group-addon">
                                        <i class="glyphicon glyphicon-euro"></i>
                                    </span></div><span class="help-block">
                                    <div id="produktKtofuehrKostFllg" class="btn-group btn-group-xs col-lg-12 col-md-12 col-sm-12 col-xs-12" data-toggle="buttons">
                                        <?php print($this->formElement($form->get("produktKtofuehrKostFllg"))); ?>
                                    </div>
                                </span>
                            <?php elseif ($name == 'produktWiderrufsfrist'):
                                ?>
                                <?php print($this->formElement($element)); ?>
                                <span class="help-block">
                                    <div id="produktWiderrufsfristZeiteinh" class="btn-group btn-group-xs col-lg-12 col-md-12 col-sm-12 col-xs-12" data-toggle="buttons">
                                        <?php print($this->formElement($form->get("produktWiderrufsfristZeiteinh"))); ?>
                                    </div>
                                </span>
                            <?php elseif ($name == 'produktLaufzeit'): ?>
                                <div class="input-group">
                                    <?php print($this->formElement($element)); ?>
                                    <span class="input-group-addon">Monate</span>
                                </div>
                                <?php
                            elseif ($name != 'produktKtofuehrKostFllg' && $name != 'produktWiderrufsfristZeiteinh'):
                                print($this->formElement($element));
                            endif;
                            ?>
                        </div>
                    </div>
                    <?php
                    if ($name == 'bank' ||
                            $name == 'ktozugriffe' ||
                            $name == 'rkvAbschluss' ||
                            $name == 'produktKlickoutUrl' ||
                            $name == 'produktGesamtbetrag'
                    ):
                        ?>
                    </div>
                </div>
            <?php endif; ?>
        <?php endforeach; ?>
        <!-- <button type="button" class="btn" id="fill-produkt"> -->
        <!-- 	Fill -->
        <!-- </button> -->
        <div class="hidden-lg hidden-md hidden-sm">
            <div class="form-group">
                <label class="col-lg-3 col-md-3 col-sm-3 col-xs-12 control-label"></label>
                <div class="col-lg-7 col-md-7 col-sm-8 col-xs-12">
                    <button class="btn btn-default btn-block konditionen-bearbeiten" type="button">Konditionen bearbeiten</button>
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 col-md-3 col-sm-3 col-xs-12 control-label"></label>
                <div class="col-lg-7 col-md-7 col-sm-8 col-xs-12">
                    <button class="btn btn-success btn-block save-changes" type="button">Speichern</button>
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 col-md-3 col-sm-3 col-xs-12 control-label"></label>
                <div class="col-lg-7 col-md-7 col-sm-8 col-xs-12">
                    <button class="btn btn-danger btn-block discard-changes" type="button">Eingaben verwerfen</button>
                </div>
            </div>
        </div>
        <?php echo $this->form()->closeTag(); ?>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-4 hidden-xs">
        <div class="affix">
            <div class="panel panel-default">
                <div class="panel-heading">Navigation</div>
                <div class="scrollspy-nav">
                    <ul class="nav nav-pills nav-stacked" id="overview-nav">
                        <li><a href="#pflichtfelder">Pflichtfelder</a></li>
                        <li><a href="#allgemeine-eigenschaften">Allgemeine Eigenschaften (optional)</a></li>
                        <li><a href="#kredit-eigenschaften">Krediteigenschaften (optional)</a></li>
                        <li><a href="#informationen">Informationen</a></li>
                        <li><a href="#repr-beispiel">Repräsentatives Beispiel</a></li>
                    </ul>
                </div>
            </div>
            <button class="btn btn-default btn-block konditionen-bearbeiten" type="button">Konditionen bearbeiten</button>
            <button class="btn btn-success btn-block save-changes" type="button">Speichern</button>
            <button class="btn btn-danger btn-block discard-changes" type="button">Eingaben verwerfen</button>
        </div>
    </div>
</div>
<?php echo $this->render('kredit/konditionsmatrix'); ?>