<?php echo $this->doctype(); ?>

<html lang="de">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Verglecihsrechner'))->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
	        ->prependStylesheet($this->basePath() . '/css/core.css')
	        ->prependStylesheet($this->basePath() . '/scripts/jquery-validationEngine/css/validationEngine.jquery.css')
	        ->prependStylesheet($this->basePath() . '/scripts/jquery-jtable/css/themes/jqueryui/jtable_jqueryui.min.css')
	        ->prependStylesheet($this->basePath() . '/scripts/jquery-ui/css/smoothness/jquery-ui.min.css')
	        ->prependStylesheet($this->basePath() . '/scripts/bootstrap/css/bootstrap-theme.min.css')
	        ->prependStylesheet($this->basePath() . '/scripts/bootstrap/css/bootstrap.min.css');
        ?>
        <!-- Scripts -->
        <!--[if !IE]> -->
		<script type="text/javascript" src="<?php echo $this->basePath() . '/scripts/jquery/jquery.2.0.3.min.js' ?>"></script>
		<!-- <![endif]-->
        <?php echo $this->headScript()
	        ->appendFile($this->basePath() . '/scripts/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9'))
	        ->appendFile($this->basePath() . '/scripts/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9'))
	        ->appendFile($this->basePath() . '/scripts/jquery/jquery.1.10.2.min.js', 'text/javascript', array('conditional' => 'lt IE 9'))
	        ->appendFile($this->basePath() . '/scripts/bootstrap/js/bootstrap.min.js')
	        ->appendFile($this->basePath() . '/scripts/jquery-ui/js/jquery-ui.js')
	        ->appendFile($this->basePath() . '/scripts/jquery-jtable/js/jquery.jtable.min.js')
	        ->appendFile($this->basePath() . '/scripts/jquery-jtable/js/localization/jquery.jtable.de.js')
	        ->appendFile($this->basePath() . '/scripts/jquery-validationEngine/js/languages/jquery.validationEngine-de.js')
	        ->appendFile($this->basePath() . '/scripts/jquery-validationEngine/js/jquery.validationEngine.js')
// 	        ->appendFile($this->basePath() . '/scripts/jquery/jquery.scrollTo.min.js')
	        ->appendFile($this->basePath() . '/scripts/layout.js')
// 	        ->prependFile($this->basePath() . '/scripts/layout.js')
// 	        ->prependFile($this->basePath() . '/scripts/jquery-validationEngine/js/jquery.validationEngine.js')
// 	        ->prependFile($this->basePath() . '/scripts/jquery-validationEngine/js/languages/jquery.validationEngine-de.js')
// 	        ->prependFile($this->basePath() . '/scripts/jquery-jtable/js/localization/jquery.jtable.de.js')
// 	        ->prependFile($this->basePath() . '/scripts/jquery-jtable/js/jquery.jtable.min.js')
// 	        ->prependFile($this->basePath() . '/scripts/jquery-ui/js/jquery-ui.js')
// 	        ->prependFile($this->basePath() . '/scripts/bootstrap/js/bootstrap.min.js')
// 	        ->prependFile($this->basePath() . '/scripts/jquery/jquery.2.0.3.min.js', 'text/javascript', array('conditional' => '!IE'))
// 	        ->prependFile($this->basePath() . '/scripts/jquery/jquery.1.10.2.min.js', 'text/javascript', array('conditional' => 'lt IE 9'))
// 	        ->prependFile($this->basePath() . '/scripts/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9'))
// 	        ->prependFile($this->basePath() . '/scripts/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9'));
		?>
    </head>
    <body>

		<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
			<div class="container">
				<div class="navbar-header">
					<a class="navbar-brand" href="<?php echo $this->url('welcome') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="vergleich24"/>&nbsp;<?php echo $this->translate('vergleich24') ?></a>
				</div>
               	<div class="collapse navbar-collapse">
					<?php 
						if($user = $this->identity()){
							echo $this->navigation('navigation')    
								->menu()
							    ->setMinDepth(0)
							    ->setMaxDepth(0)
							    ->setUlClass('nav navbar-nav')
							    ->render();
						}
					?>
					<ul class="nav navbar-nav navbar-right">
	                	<?php 
                			if($user = $this->identity()){
						?>
						<li><p class="navbar-text navbar-right"><?php echo 'Angemeldet als ' . $this->escapeHtml($user->getUserVorname()." ".$user->getUserName()); ?></p></li>
						<li>
							<?php //echo $this->navigation('navigation')->menu(); ?>
							<a href="<?php echo $this->url('logout') ?>"><?php echo $this->translate('Logout') ?></a>
							<?php 		
								}
                			?>
						</li>
					</ul>
				</div>
			</div>
		</div>
        <div class="container">
        	<div class="container">
	        	<?php echo $this->navigation('navigation')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb.phtml'); ?>
            </div>
            <div class="container">
            	<div class="alert" id="alert">
            		<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            		<div id="alert-message"></div>
            	</div>
            </div>
            <div class="container">
	            <?php echo $this->content; ?>
            </div>
		</div>
		<div class="container">
			<hr>
		</div>
		<?php echo $this->inlineScript() ?>
    </body>
</html>
