<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Verglecihsrechner'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
	        ->prependStylesheet($this->basePath() . '/css/core.css')
	        ->prependStylesheet($this->basePath() . '/scripts/jquery-validationEngine/css/validationEngine.jquery.css')
	        ->prependStylesheet($this->basePath() . '/scripts/jquery-jtable/css/themes/jqueryui/jtable_jqueryui.min.css')
	        ->prependStylesheet($this->basePath() . '/scripts/jquery-ui/css/smoothness/jquery-ui.min.css')
	        ->prependStylesheet($this->basePath() . '/scripts/bootstrap/css/bootstrap-theme.min.css')
	        ->prependStylesheet($this->basePath() . '/scripts/bootstrap/css/bootstrap.min.css');
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
        	->prependFile($this->basePath() . '/scripts/layout.js')
	        ->prependFile($this->basePath() . '/scripts/jquery-validationEngine/js/jquery.validationEngine.js')
	        ->prependFile($this->basePath() . '/scripts/jquery-validationEngine/js/languages/jquery.validationEngine-de.js')
	        ->prependFile($this->basePath() . '/scripts/jquery-jtable/js/localization/jquery.jtable.de.js')
	        ->prependFile($this->basePath() . '/scripts/jquery-jtable/js/jquery.jtable.min.js')
	        ->prependFile($this->basePath() . '/scripts/bootstrap/js/bootstrap.min.js')
	        ->prependFile($this->basePath() . '/scripts/jquery-ui/js/jquery-ui.min.js')
	        ->prependFile($this->basePath() . '/scripts/jquery/jquery.min.js');
        ?>

    </head>
    <body>
        <header class="navbar navbar-inverse navbar-fixed-top bs-docs-nav" role="banner">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="<?php echo $this->url('welcome') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="vergleich24"/>&nbsp;<?php echo $this->translate('vergleich24') ?></a>
               	</div>
               	<nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
					<?php 
						echo $this->navigation('navigation')    
							->menu()
						    ->setMinDepth(0)
						    ->setMaxDepth(0)
						    ->setUlClass('nav navbar-nav')
						    ->render();
					?>
					<ul class="nav navbar-nav navbar-right">
	                	<?php 
                			if($user = $this->identity()){
						?>
						<li><p class="navbar-text navbar-right"><?php echo 'Angemeldet als ' . $this->escapeHtml($user->getUserVorname()." ".$user->getUserName()); ?></p></li>
						<li>
							<?php //echo $this->navigation('navigation')->menu(); ?>
							<a href="<?php echo $this->url('logout') ?>"><?php echo $this->translate('Logout') ?></a>
							<?php 		
								}
                			?>
						</li>
					</ul>
                </nav>

            </div>
        </header>
        <div class="container">
        	<?php 
        		echo $this->navigation('navigation')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb.phtml');
            	echo $this->content;
            ?>
        </div>
        <div class="container">
        	<hr>
       	</div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
