	<?php
		echo $this->headLink()->prependStylesheet($this->basePath() . '/css/login.css');
		echo $this->headScript()
			->prependFile($this->basePath() . '/scripts/login.js');
		$form = $this->form;
		//$form->setAttribute('action', $this->url('login', array('controller' => 'auth', 'action' => 'login')));
		echo $this->form()->openTag($form);
	?>
	<div class="form-group">
		<div class="col-sm-offset-3 col-sm-4">
			<h2>Please login</h2>
		</div>
	</div>
<?php foreach ($form as $element) :?>
	        <?php
	            $type = $element->getAttribute('type');
	            $name = $element->getAttribute('name'); 
	            $label = $element->getLabel();
	        ?>
	        <div class="form-group">
	        	<?php if($name == 'login-button' || $name == 'rememberme') : ?>
	        		<div class="col-sm-3"></div>
	        	<?php else:
	        		echo $this->formLabel($element); 
	        	?>
	        	<?php endif; ?>	
	        	
	        	<?php if($name == 'rememberme'):?>
	        		<div class="col-sm-4">
						 <label class="checkbox">
			        		<?php 
		        				echo $this->formElement($element) . 'Remember me?' ;
		        			?>
		        		 </label>
					</div>
	        	<?php else : ?>
		        	<div class="col-sm-4">
		        		<?php 
	        				echo $this->formElement($element);
	        			?>
	        		</div>
        		<?php endif; ?>
        	</div>
<?php endforeach; ?>	
<?php echo $this->form()->closeTag(); ?>