<h1>I am in Vergleichsrechner AuthController index action index.phtml</h1>

<?php echo $this->message; ?>

<?php var_dump($this->users); ?>

<?php
echo '<pre>';
print_r($this->users);
echo '</pre>';
?>
<hr />
<table>
        <tr>
			<th>getUserEmail</th>
        </tr>
<?php foreach ($users as $user) { ?>
        <tr>
                <td><?php echo $this->escapeHtml($user->getUserPassword());?></td>
        </tr>
<?php } ?>
</table>